name: PR Handler
on:
  pull_request:
    branches:
      - prod
    types:
      - opened        
      - closed       

jobs:
  notify-dope:
    runs-on: ubuntu-latest
    # Add conditions to prevent duplicate runs
    if: |
      (github.event.action == 'opened') ||
      (github.event.action == 'closed' && github.event.pull_request.merged == true)
    steps:
      - name: Trigger Dope Workflow
        run: |
          if [[ "${{ github.event.action }}" == "opened" ]]; then
            ACTION="plan"
            EVENT_TYPE="pr-trigger"
          elif [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            ACTION="apply"
            EVENT_TYPE="terraform-trigger"
          fi

          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -w "\nHTTP_STATUS:%{http_code}" \
            https://api.github.com/repos/${{ github.repository_owner }}/Dope/dispatches \
            -d '{
              "event_type": "'"$EVENT_TYPE"'",
              "client_payload": {
                "repository": "${{ github.event.repository.name }}",
                "ref": "prod",
                "pr_number": "${{ github.event.pull_request.number }}",
                "action": "'"$ACTION"'",
                "pr_merged": ${{ github.event.pull_request.merged }}
              }
            }'
